import os

SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL")
SECRET_KEY = "Ccdivw2Cmz53oUtXGPromUcEeGKkXM8H"
PUBLIC_ROLE_LIKE = "Gamma"
HTTP_HEADERS = {'X-Frame-Options': 'ALLOWALL'}
OVERRIDE_HTTP_HEADERS = {'X-Frame-Options': 'ALLOWALL'}
